2025-06-03 20:52:12,825 INFO    MainThread:1609413 [wandb_setup.py:_flush():81] Current SDK version is 0.20.0
2025-06-03 20:52:12,825 INFO    MainThread:1609413 [wandb_setup.py:_flush():81] Configure stats pid to 1609413
2025-06-03 20:52:12,825 INFO    MainThread:1609413 [wandb_setup.py:_flush():81] Loading settings from /home/rathul/.config/wandb/settings
2025-06-03 20:52:12,825 INFO    MainThread:1609413 [wandb_setup.py:_flush():81] Loading settings from /home/rathul/pvp4real/wandb/settings
2025-06-03 20:52:12,828 INFO    MainThread:1609413 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-06-03 20:52:12,828 INFO    MainThread:1609413 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /home/rathul/pvp4real/wandb/run-20250603_205212-pvp4real_freelevel0.95_2025-06-03_20-52-11_7540bf06/logs/debug.log
2025-06-03 20:52:12,830 INFO    MainThread:1609413 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /home/rathul/pvp4real/wandb/run-20250603_205212-pvp4real_freelevel0.95_2025-06-03_20-52-11_7540bf06/logs/debug-internal.log
2025-06-03 20:52:12,839 INFO    MainThread:1609413 [wandb_init.py:init():831] calling init triggers
2025-06-03 20:52:12,840 INFO    MainThread:1609413 [wandb_init.py:init():836] wandb.init called with sweep_config: {}
config: {'env_config': {'use_render': False, 'free_level': 0.95}, 'algo': {'adaptive_batch_size': 'False', 'bc_loss_weight': 1.0, 'only_bc_loss': 'False', 'with_human_proxy_value_loss': 'True', 'with_agent_proxy_value_loss': 'True', 'add_bc_loss': 'True', 'use_balance_sample': True, 'agent_data_ratio': 1.0, 'policy': <class 'pvp.sb3.td3.policies.TD3Policy'>, 'replay_buffer_class': <class 'pvp.sb3.haco.haco_buffer.HACOReplayBuffer'>, 'replay_buffer_kwargs': {'discard_reward': True}, 'policy_kwargs': {'net_arch': [256, 256]}, 'env': <SharedControlMonitor<Monitor<FakeHumanEnv instance>>>, 'learning_rate': 0.0001, 'q_value_bound': 1, 'optimize_memory_usage': True, 'buffer_size': 50000, 'learning_starts': 10, 'batch_size': 1024, 'tau': 0.005, 'gamma': 0.99, 'train_freq': (1, 'step'), 'action_noise': None, 'tensorboard_log': PosixPath('logs/runs/pvp4real_freelevel0.95/pvp4real_freelevel0.95_2025-06-03_20-52-11_7540bf06'), 'create_eval_env': False, 'verbose': 2, 'seed': 0, 'device': 'auto'}, 'exp_name': 'pvp4real_freelevel0.95', 'seed': 0, 'use_wandb': True, 'trial_name': 'pvp4real_freelevel0.95_2025-06-03_20-52-11_7540bf06', 'log_dir': 'logs/runs/pvp4real_freelevel0.95/pvp4real_freelevel0.95_2025-06-03_20-52-11_7540bf06', '_wandb': {'code_path': 'code/pvp/experiments/metadrive/train_pvp_metadrive_fakehuman.py'}}
2025-06-03 20:52:12,840 INFO    MainThread:1609413 [wandb_init.py:init():872] starting backend
2025-06-03 20:52:13,358 INFO    MainThread:1609413 [wandb_init.py:init():875] sending inform_init request
2025-06-03 20:52:13,443 INFO    MainThread:1609413 [wandb_init.py:init():883] backend started and connected
2025-06-03 20:52:13,451 INFO    MainThread:1609413 [wandb_init.py:init():956] updated telemetry
2025-06-03 20:52:13,526 INFO    MainThread:1609413 [wandb_init.py:init():980] communicating run to backend with 90.0 second timeout
2025-06-03 20:52:14,033 INFO    MainThread:1609413 [wandb_init.py:init():1032] starting run threads in backend
2025-06-03 20:52:14,969 INFO    MainThread:1609413 [wandb_run.py:_config_callback():1358] config_cb None None {'_wandb': {'code_path': 'source-pvp4real_MetaUrban-pvp_experiments_metadrive_train_pvp_metadrive_fakehuman.py'}}
2025-06-03 20:52:15,195 INFO    MainThread:1609413 [wandb_run.py:_console_start():2453] atexit reg
2025-06-03 20:52:15,196 INFO    MainThread:1609413 [wandb_run.py:_redirect():2301] redirect: wrap_raw
2025-06-03 20:52:15,196 INFO    MainThread:1609413 [wandb_run.py:_redirect():2370] Wrapping output streams.
2025-06-03 20:52:15,196 INFO    MainThread:1609413 [wandb_run.py:_redirect():2393] Redirects installed.
2025-06-03 20:52:15,201 INFO    MainThread:1609413 [wandb_init.py:init():1078] run started, returning control to user process
2025-06-03 20:52:16,032 INFO    MainThread:1609413 [wandb_run.py:_config_callback():1358] config_cb None None {'_wandb': {'code_path': 'source-pvp4real_MetaUrban-pvp_experiments_metadrive_train_pvp_metadrive_fakehuman.py'}}
2025-06-03 20:52:16,284 INFO    MainThread:1609413 [wandb_run.py:_tensorboard_callback():1567] tensorboard callback: logs/runs/pvp4real_freelevel0.95/pvp4real_freelevel0.95_2025-06-03_20-52-11_7540bf06/pvp4real_freelevel0.95_1, True
2025-06-03 20:52:16,293 INFO    MainThread:1609413 [wandb_run.py:_config_callback():1358] config_cb None None {'cql_coefficient': 1, 'extra_config': "{'adaptive_batch_size': False, 'add_bc_loss': True, 'only_bc_loss': False, 'with_human_proxy_value_loss': True, 'with_agent_proxy_value_loss': True, 'agent_data_ratio': 1.0, 'bc_loss_weight': 1.0}", 'q_value_bound': 1, 'use_balance_sample': 'True', 'policy_class': "<class 'pvp.sb3.td3.policies.TD3Policy'>", 'device': 'cuda', 'env': '<pvp.sb3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x7dd0eed41cd0>', '_vec_normalize_env': 'None', 'verbose': 2, 'policy_kwargs': "{'net_arch': [256, 256]}", 'observation_space': 'Box(-0.0, 1.0, (259,), float32)', 'action_space': 'Box(-1.0, 1.0, (2,), float32)', 'n_envs': 1, 'num_timesteps': 0, 'since_last_reset': 0, '_total_timesteps': 50000, '_num_timesteps_at_start': 0, 'eval_env': 'None', 'action_noise': 'None', 'start_time': 1749009136.0642018, 'policy': 'TD3Policy(\n  (actor): Actor(\n    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (mu): Sequential(\n      (0): Linear(in_features=259, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256, out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256, out_features=2, bias=True)\n      (5): Tanh()\n    )\n  )\n  (actor_target): Actor(\n    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (mu): Sequential(\n      (0): Linear(in_features=259, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256, out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256, out_features=2, bias=True)\n      (5): Tanh()\n    )\n  )\n  (critic): ContinuousCritic(\n    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=261, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256, out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256, out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=261, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256, out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256, out_features=1, bias=True)\n    )\n  )\n  (critic_target): ContinuousCritic(\n    (features_extractor): FlattenExtractor(\n      (flatten): Flatten(start_dim=1, end_dim=-1)\n    )\n    (qf0): Sequential(\n      (0): Linear(in_features=261, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256, out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256, out_features=1, bias=True)\n    )\n    (qf1): Sequential(\n      (0): Linear(in_features=261, out_features=256, bias=True)\n      (1): ReLU()\n      (2): Linear(in_features=256, out_features=256, bias=True)\n      (3): ReLU()\n      (4): Linear(in_features=256, out_features=1, bias=True)\n    )\n  )\n)', 'learning_rate': 0.0001, 'tensorboard_log': 'logs/runs/pvp4real_freelevel0.95/pvp4real_freelevel0.95_2025-06-03_20-52-11_7540bf06', 'lr_schedule': '<function constant_fn.<locals>.func at 0x7dd0ef79c670>', '_last_obs': '[[0.29166666 0.29166666 0.5        0.01234568 0.5        0.5\n  0.5        0.         0.5        0.55       0.5        0.\n  0.5        0.5        0.95       0.5        0.         0.5\n  0.5        1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.         1.         1.         1.         1.         1.\n  1.        ]]', '_last_episode_starts': '[ True]', '_last_original_obs': 'None', '_episode_num': 0, 'use_sde': 'False', 'sde_sample_freq': -1, '_current_progress_remaining': 1, 'ep_info_buffer': 'deque([], maxlen=100)', 'ep_success_buffer': 'deque([], maxlen=100)', '_n_updates': 0, '_logger': '<pvp.sb3.common.logger.Logger object at 0x7dd0ee3a6fd0>', '_custom_logger': 'False', 'buffer_size': 50000, 'batch_size': 1024, 'learning_starts': 10, 'tau': 0.005, 'gamma': 0.99, 'gradient_steps': -1, 'optimize_memory_usage': 'True', 'replay_buffer_class': "<class 'pvp.sb3.haco.haco_buffer.HACOReplayBuffer'>", 'replay_buffer_kwargs': "{'discard_reward': True}", '_episode_storage': 'None', 'remove_time_limit_termination': 'False', 'train_freq': "TrainFreq(frequency=1, unit=<TrainFrequencyUnit.STEP: 'step'>)", 'actor': 'Actor(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (mu): Sequential(\n    (0): Linear(in_features=259, out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256, out_features=2, bias=True)\n    (5): Tanh()\n  )\n)', 'replay_buffer': '<pvp.sb3.haco.haco_buffer.HACOReplayBuffer object at 0x7dd0ef3ceac0>', 'use_sde_at_warmup': 'False', 'policy_delay': 2, 'target_noise_clip': 0.5, 'target_policy_noise': 0.2, 'actor_target': 'Actor(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (mu): Sequential(\n    (0): Linear(in_features=259, out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256, out_features=2, bias=True)\n    (5): Tanh()\n  )\n)', 'critic': 'ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=261, out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=261, out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n  )\n)', 'critic_target': 'ContinuousCritic(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (qf0): Sequential(\n    (0): Linear(in_features=261, out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n  )\n  (qf1): Sequential(\n    (0): Linear(in_features=261, out_features=256, bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=256, out_features=256, bias=True)\n    (3): ReLU()\n    (4): Linear(in_features=256, out_features=1, bias=True)\n  )\n)', 'human_data_buffer': '<pvp.sb3.haco.haco_buffer.HACOReplayBuffer object at 0x7dd0ef3244f0>'}
2025-06-03 20:52:29,202 INFO    MsgRouterThr:1609413 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-06-03 20:52:29,637 ERROR   MainThread:1609413 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-03 20:52:29,644 ERROR   MainThread:1609413 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-03 20:52:29,650 ERROR   MainThread:1609413 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-03 20:52:29,650 ERROR   MainThread:1609413 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-03 20:52:29,653 ERROR   MainThread:1609413 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-03 20:52:29,656 ERROR   MainThread:1609413 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-03 20:52:29,659 ERROR   MainThread:1609413 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-03 20:52:29,661 ERROR   MainThread:1609413 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-03 20:52:29,664 ERROR   MainThread:1609413 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-03 20:52:29,667 ERROR   MainThread:1609413 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-03 20:52:29,671 ERROR   MainThread:1609413 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-03 20:52:29,673 ERROR   MainThread:1609413 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-03 20:52:29,676 ERROR   MainThread:1609413 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-03 20:52:29,679 ERROR   MainThread:1609413 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-03 20:52:29,681 ERROR   MainThread:1609413 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-06-03 20:52:29,684 ERROR   MainThread:1609413 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2380, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/rathul/miniconda3/envs/pvp4real/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
